# Generated by Django 4.1.7 on 2023-04-12 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='missingperson',
            table='MissingTable',
        ),
    ]
